import type { ProvisioningPlan } from '../provisioning/graph.types.js';
import type { ProjectModule } from './project-manager.js';
import { projectResourceSlug } from './project-identity.js';
import { resolveProjectRuntimeEnvValues } from '../provisioning/runtime-env.js';

export interface ProjectEnvBundle {
  fileName: string;
  contents: string;
  missingRequiredKeys: string[];
}

export interface ProjectEnvSecretOverrides {
  firebaseApiKey?: string;
}

function mergeCompletedUpstream(plan: ProvisioningPlan): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [, state] of plan.nodeStates) {
    if ((state.status === 'completed' || state.status === 'skipped') && state.resourcesProduced) {
      Object.assign(out, state.resourcesProduced);
    }
  }
  return out;
}

function toEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function setEnvLine(lines: string[], key: string, value: string, required: boolean, missing: string[]): void {
  if (value) {
    lines.push(`${key}=${toEnvValue(value)}`);
    return;
  }
  lines.push(`${key}=`);
  if (required) {
    missing.push(key);
  }
}

export function buildProjectEnvBundle(
  plan: ProvisioningPlan,
  projectModule: ProjectModule,
  readVault: (providerId: string, key: string) => string | undefined,
  overrides: ProjectEnvSecretOverrides = {},
): ProjectEnvBundle {
  const projectId = plan.projectId;
  const upstream = mergeCompletedUpstream(plan);
  const slug = projectResourceSlug(projectModule.project) || projectId;
  const lines: string[] = [];
  const platforms = projectModule.project.platforms ?? [];
  const runtimeValues = resolveProjectRuntimeEnvValues({
    projectId,
    upstream,
    readVault,
    firebaseApiKeyOverride: overrides.firebaseApiKey,
    includesAndroid: platforms.includes('android'),
    includesIos: platforms.includes('ios'),
  });
  const missingRequired = [...runtimeValues.missingRequiredKeys];

  lines.push(
    '# Generated by Studio: Project Secrets Bundle',
    `# Project: ${projectModule.project.name || slug} (${projectId})`,
    '# Review before committing. Treat this file as sensitive.',
    '',
    '# Firebase runtime',
  );
  setEnvLine(lines, 'FIREBASE_API_KEY', runtimeValues.values['FIREBASE_API_KEY'] ?? '', false, missingRequired);
  setEnvLine(lines, 'FIREBASE_PROJECT_ID', runtimeValues.values['FIREBASE_PROJECT_ID'] ?? '', false, missingRequired);
  setEnvLine(lines, 'FIREBASE_IOS_APP_ID', runtimeValues.values['FIREBASE_IOS_APP_ID'] ?? '', false, missingRequired);
  setEnvLine(
    lines,
    'FIREBASE_ANDROID_APP_ID',
    runtimeValues.values['FIREBASE_ANDROID_APP_ID'] ?? '',
    false,
    missingRequired,
  );

  lines.push('', '# OAuth / auth routing');
  setEnvLine(
    lines,
    'GOOGLE_WEB_CLIENT_ID',
    runtimeValues.values['GOOGLE_WEB_CLIENT_ID'] ?? '',
    false,
    missingRequired,
  );
  setEnvLine(
    lines,
    'GOOGLE_IOS_CLIENT_ID',
    runtimeValues.values['GOOGLE_IOS_CLIENT_ID'] ?? '',
    false,
    missingRequired,
  );
  setEnvLine(
    lines,
    'GOOGLE_ANDROID_CLIENT_ID',
    runtimeValues.values['GOOGLE_ANDROID_CLIENT_ID'] ?? '',
    false,
    missingRequired,
  );
  setEnvLine(lines, 'APPLE_SERVICE_ID', runtimeValues.values['APPLE_SERVICE_ID'] ?? '', false, missingRequired);
  setEnvLine(
    lines,
    'AUTH_DEEP_LINK_BASE_URL',
    runtimeValues.values['AUTH_DEEP_LINK_BASE_URL'] ?? '',
    false,
    missingRequired,
  );
  setEnvLine(lines, 'AUTH_LANDING_URL', runtimeValues.values['AUTH_LANDING_URL'] ?? '', false, missingRequired);

  if (missingRequired.length > 0) {
    lines.push(
      '',
      '# Missing required values detected by Studio:',
      ...missingRequired.map((key) => `# - ${key}`),
      '# Fill these keys before using this env file in app runtime/CI.',
    );
  }

  return {
    fileName: `${slug}.env`,
    contents: `${lines.join('\n')}\n`,
    missingRequiredKeys: missingRequired,
  };
}
