import type { ProvisioningPlan } from '../provisioning/graph.types.js';
import type { ProjectModule } from './project-manager.js';
import { projectResourceSlug } from './project-identity.js';

export interface ProjectEnvBundle {
  fileName: string;
  contents: string;
  missingRequiredKeys: string[];
}

export interface ProjectEnvSecretOverrides {
  firebaseApiKey?: string;
}

function mergeCompletedUpstream(plan: ProvisioningPlan): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [, state] of plan.nodeStates) {
    if ((state.status === 'completed' || state.status === 'skipped') && state.resourcesProduced) {
      Object.assign(out, state.resourcesProduced);
    }
  }
  return out;
}

function toEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function firstPresent(...values: Array<string | undefined | null>): string {
  for (const value of values) {
    const trimmed = value?.trim() ?? '';
    if (trimmed) return trimmed;
  }
  return '';
}

function setEnvLine(lines: string[], key: string, value: string, required: boolean, missing: string[]): void {
  if (value) {
    lines.push(`${key}=${toEnvValue(value)}`);
    return;
  }
  lines.push(`${key}=`);
  if (required) {
    missing.push(key);
  }
}

export function buildProjectEnvBundle(
  plan: ProvisioningPlan,
  projectModule: ProjectModule,
  readVault: (providerId: string, key: string) => string | undefined,
  overrides: ProjectEnvSecretOverrides = {},
): ProjectEnvBundle {
  const upstream = mergeCompletedUpstream(plan);
  const projectId = plan.projectId;
  const slug = projectResourceSlug(projectModule.project) || projectId;
  const lines: string[] = [];
  const missingRequired: string[] = [];

  const firebaseApiKey = firstPresent(
    overrides.firebaseApiKey,
    readVault('firebase', `${projectId}/api_key`),
    readVault('firebase', 'api_key'),
  );
  const firebaseProjectId = firstPresent(upstream['firebase_project_id'], upstream['gcp_project_id']);
  const firebaseIosAppId = firstPresent(upstream['firebase_ios_app_id']);
  const firebaseAndroidAppId = firstPresent(upstream['firebase_android_app_id']);
  const googleWebClientId = firstPresent(upstream['oauth_client_id_web']);
  const googleIosClientId = firstPresent(upstream['oauth_client_id_ios']);
  const googleAndroidClientId = firstPresent(upstream['oauth_client_id_android']);
  const appleServiceId = firstPresent(upstream['apple_sign_in_service_id']);
  const deepLinkBaseUrl = firstPresent(upstream['deep_link_base_url']);
  const authLandingUrl = firstPresent(upstream['auth_landing_url']);
  const platforms = projectModule.project.platforms ?? [];
  const includesAndroid = platforms.includes('android');
  const includesIos = platforms.includes('ios');
  const googleEnabled = Boolean(googleWebClientId || googleIosClientId || googleAndroidClientId);

  lines.push(
    '# Generated by Studio: Project Secrets Bundle',
    `# Project: ${projectModule.project.name || slug} (${projectId})`,
    '# Review before committing. Treat this file as sensitive.',
    '',
    '# Firebase runtime',
  );
  setEnvLine(lines, 'FIREBASE_API_KEY', firebaseApiKey, true, missingRequired);
  setEnvLine(lines, 'FIREBASE_PROJECT_ID', firebaseProjectId, true, missingRequired);
  setEnvLine(lines, 'FIREBASE_IOS_APP_ID', firebaseIosAppId, false, missingRequired);
  setEnvLine(lines, 'FIREBASE_ANDROID_APP_ID', firebaseAndroidAppId, false, missingRequired);

  lines.push('', '# OAuth / auth routing');
  setEnvLine(lines, 'GOOGLE_WEB_CLIENT_ID', googleWebClientId, googleEnabled, missingRequired);
  setEnvLine(lines, 'GOOGLE_IOS_CLIENT_ID', googleIosClientId, googleEnabled && includesIos, missingRequired);
  setEnvLine(
    lines,
    'GOOGLE_ANDROID_CLIENT_ID',
    googleAndroidClientId,
    googleEnabled && includesAndroid,
    missingRequired,
  );
  setEnvLine(lines, 'APPLE_SERVICE_ID', appleServiceId, false, missingRequired);
  setEnvLine(lines, 'AUTH_DEEP_LINK_BASE_URL', deepLinkBaseUrl, false, missingRequired);
  setEnvLine(lines, 'AUTH_LANDING_URL', authLandingUrl, false, missingRequired);

  if (missingRequired.length > 0) {
    lines.push(
      '',
      '# Missing required values detected by Studio:',
      ...missingRequired.map((key) => `# - ${key}`),
      '# Fill these keys before using this env file in app runtime/CI.',
    );
  }

  return {
    fileName: `${slug}.env`,
    contents: `${lines.join('\n')}\n`,
    missingRequiredKeys: missingRequired,
  };
}
