import type { ProvisioningStepNode } from '../graph.types.js';

export const GCP_SERVERLESS_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'gcp:resolve-project-context',
    label: 'Resolve Cloud Project Context',
    description: 'Resolve and validate project-level Google Cloud deployment context.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'firebase:create-gcp-project', required: true }],
    produces: [
      { key: 'gcp_project_id', label: 'GCP Project ID', description: 'Target GCP project for serverless delivery.' },
      { key: 'gcp_region', label: 'GCP Region', description: 'Deployment region for serverless runtime.' },
    ],
  },
  {
    type: 'step',
    key: 'gcp:prepare-runtime-foundation',
    label: 'Prepare Runtime Foundation',
    description: 'Validate billing/access prerequisites and enable baseline runtime services for serverless delivery.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:resolve-project-context', required: true }],
    produces: [{ key: 'gcp_foundation_ready', label: 'Foundation Ready', description: 'Serverless runtime foundation status.' }],
  },
  {
    type: 'step',
    key: 'gcp:ensure-artifact-registry',
    label: 'Prepare Container Registry',
    description: 'Create or validate Artifact Registry repository for service images.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:prepare-runtime-foundation', required: true }],
    produces: [{ key: 'artifact_registry_repo', label: 'Artifact Repo', description: 'Artifact Registry repository path.' }],
  },
  {
    type: 'step',
    key: 'gcp:ensure-runtime-service-account',
    label: 'Prepare Runtime Service Account',
    description: 'Create or validate runtime service account and required IAM permissions.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:prepare-runtime-foundation', required: true }],
    produces: [{ key: 'runtime_service_account_email', label: 'Runtime Service Account', description: 'Cloud Run runtime service account email.' }],
  },
  {
    type: 'step',
    key: 'gcp:ensure-secret-manager-bindings',
    label: 'Grant Runtime Secret Access',
    description: 'Create project secrets and bind runtime identity access to each required secret.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:ensure-runtime-service-account', required: true }],
    produces: [{ key: 'secret_manager_bindings', label: 'Secret Bindings', description: 'Secret Manager binding status.' }],
  },
  {
    type: 'step',
    key: 'gcp:setup-observability-baseline',
    label: 'Configure Runtime Observability',
    description: 'Create baseline log metrics and alert policies for serverless runtime monitoring.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:ensure-runtime-service-account', required: true }],
    produces: [{ key: 'gcp_observability_ready', label: 'Observability Ready', description: 'Baseline observability state.' }],
  },
  {
    type: 'step',
    key: 'api:build-container',
    label: 'Build API Container',
    description: 'Build backend service container image using Cloud Build.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'gcp:ensure-artifact-registry', required: true }],
    produces: [{ key: 'api_image_uri', label: 'API Image URI', description: 'Fully qualified container image URI.' }],
  },
  {
    type: 'step',
    key: 'api:deploy-cloud-run',
    label: 'Deploy API to Cloud Run',
    description: 'Deploy API revision to Cloud Run.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'api:build-container', required: true },
      { nodeKey: 'gcp:ensure-secret-manager-bindings', required: true },
    ],
    produces: [
      { key: 'api_cloud_run_service', label: 'API Cloud Run Service', description: 'Cloud Run service name.' },
      { key: 'api_cloud_run_url', label: 'API URL', description: 'Cloud Run service URL.' },
    ],
  },
  {
    type: 'step',
    key: 'api:run-smoke-check',
    label: 'Run API Smoke Check',
    description: 'Execute API health/smoke checks against deployed service.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'api:deploy-cloud-run', required: true }],
    produces: [{ key: 'api_smoke_check_passed', label: 'API Smoke Check', description: 'API smoke check result.' }],
  },
  {
    type: 'step',
    key: 'api:promote-traffic',
    label: 'Promote API Traffic',
    description: 'Promote API traffic to the newly deployed stable revision.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'api:run-smoke-check', required: true }],
    produces: [{ key: 'api_active_revision', label: 'Active API Revision', description: 'Current active Cloud Run revision.' }],
  },
  {
    type: 'step',
    key: 'api:rollback-revision',
    label: 'Rollback API Revision',
    description: 'Rollback API traffic to previous stable revision.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'api:deploy-cloud-run', required: true }],
    produces: [{ key: 'api_rollback_revision', label: 'Rollback Revision', description: 'Revision selected for rollback.' }],
  },
  {
    type: 'step',
    key: 'api:bind-domain-ssl',
    label: 'Bind API Domain and SSL',
    description: 'Configure API custom domain mapping and managed SSL.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'api:promote-traffic', required: true }],
    produces: [{ key: 'api_domain_url', label: 'API Domain URL', description: 'Bound API custom domain URL.' }],
  },
  {
    type: 'step',
    key: 'web:cicd-prepare-contract',
    label: 'Prepare Web CI Contract',
    description: 'Validate CI contract inputs and runtime prerequisites for Cloud Run web deployment.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'gcp:ensure-artifact-registry', required: true },
      { nodeKey: 'gcp:ensure-runtime-service-account', required: true },
      { nodeKey: 'gcp:ensure-secret-manager-bindings', required: true },
      { nodeKey: 'github:deploy-workflows', required: true },
    ],
    produces: [
      { key: 'web_cicd_contract_ready', label: 'Web CI Contract', description: 'CI contract wiring status.' },
      { key: 'ci_github_repo', label: 'CI Repository', description: 'GitHub repository targeted by CI deploy contract.' },
    ],
  },
  {
    type: 'step',
    key: 'web:cicd-verify-deploy',
    label: 'Verify Web CI Deployment',
    description: 'Verify Cloud Run web service exists after CI deployment and capture runtime URL.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'web:cicd-prepare-contract', required: true },
      { nodeKey: 'cicd:configure-deploy-identity', required: true },
      { nodeKey: 'cicd:wire-environment-promotions', required: true },
      { nodeKey: 'cicd:wire-rollback-action', required: true },
    ],
    produces: [
      { key: 'web_cloud_run_service', label: 'Web Cloud Run Service', description: 'Web Cloud Run service name.' },
      { key: 'web_cloud_run_url', label: 'Web URL', description: 'Web service URL.' },
    ],
  },
  {
    type: 'step',
    key: 'web:cicd-verify-smoke',
    label: 'Verify Web Smoke Check',
    description: 'Run smoke checks against the Cloud Run web URL produced by CI deployment.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'web:cicd-verify-deploy', required: true }],
    produces: [{ key: 'web_smoke_check_passed', label: 'Web Smoke Check', description: 'Web smoke check result.' }],
  },
  {
    type: 'step',
    key: 'web:bind-domain-ssl',
    label: 'Bind Web Domain and SSL',
    description: 'Configure web custom domain mapping and managed SSL.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'web:cicd-verify-smoke', required: true }],
    produces: [{ key: 'web_domain_url', label: 'Web Domain URL', description: 'Bound web custom domain URL.' }],
  },
  {
    type: 'step',
    key: 'combo:cross-service-smoke-check',
    label: 'Run Full-Stack Smoke Check',
    description: 'Run end-to-end web-to-API smoke checks.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'api:promote-traffic', required: true },
      { nodeKey: 'web:cicd-verify-smoke', required: true },
    ],
    produces: [{ key: 'combo_smoke_check_passed', label: 'Cross-Service Smoke Check', description: 'Combined flow smoke check result.' }],
  },
  {
    type: 'step',
    key: 'combo:promote-release',
    label: 'Promote Full-Stack Release',
    description: 'Mark coordinated web/API release as active.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'combo:cross-service-smoke-check', required: true }],
    produces: [{ key: 'combo_release_promoted', label: 'Release Promoted', description: 'Combined release promotion status.' }],
  },
  {
    type: 'step',
    key: 'combo:rollback-release',
    label: 'Rollback Full-Stack Release',
    description: 'Rollback coordinated web/API release.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'combo:promote-release', required: true }],
    produces: [{ key: 'combo_release_rolled_back', label: 'Release Rolled Back', description: 'Combined release rollback status.' }],
  },
  {
    type: 'step',
    key: 'cicd:generate-github-workflow',
    label: 'Generate Cloud Run CI Workflow',
    description: 'Generate GitHub Actions workflow for Cloud Run build/test/deploy/smoke/rollback.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'gcp:resolve-project-context', required: true },
      { nodeKey: 'github:deploy-workflows', required: true },
    ],
    produces: [{ key: 'cloudrun_workflow_path', label: 'Workflow File', description: 'Generated workflow path.' }],
  },
  {
    type: 'step',
    key: 'cicd:configure-deploy-identity',
    label: 'Configure CI Deployment Identity',
    description: 'Configure CI deploy identity and permissions for serverless delivery actions.',
    provider: 'gcp',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'cicd:generate-github-workflow', required: true },
      { nodeKey: 'user:share-cicd-integration-prompt', required: true },
      { nodeKey: 'gcp:ensure-runtime-service-account', required: true },
      { nodeKey: 'gcp:prepare-runtime-foundation', required: true },
      { nodeKey: 'gcp:ensure-artifact-registry', required: true },
      { nodeKey: 'gcp:ensure-secret-manager-bindings', required: true },
    ],
    produces: [
      { key: 'ci_deploy_identity_configured', label: 'CI Identity Configured', description: 'CI deploy identity setup status.' },
      { key: 'gcp_ci_service_account', label: 'CI Service Account', description: 'Service account used by GitHub Actions deploy jobs.' },
      { key: 'gcp_workload_identity_provider', label: 'WIF Provider', description: 'Workload Identity provider resource bound to the repo.' },
      { key: 'cloudbuild_source_bucket', label: 'Cloud Build Source Bucket', description: 'Cloud Build source-staging bucket for gcloud builds submit.' },
    ],
  },
  {
    type: 'step',
    key: 'cicd:wire-environment-promotions',
    label: 'Add CI Promotion Controls',
    description: 'Wire environment promotion controls in CI workflow.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'cicd:generate-github-workflow', required: true },
      { nodeKey: 'api:promote-traffic', required: false },
    ],
    produces: [{ key: 'ci_promotions_wired', label: 'CI Promotions Wired', description: 'Promotion wiring status.' }],
  },
  {
    type: 'step',
    key: 'cicd:wire-rollback-action',
    label: 'Add CI Rollback Action',
    description: 'Wire deterministic rollback action in CI workflow.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [
      { nodeKey: 'cicd:wire-environment-promotions', required: true },
      { nodeKey: 'api:rollback-revision', required: false },
    ],
    produces: [{ key: 'ci_rollback_wired', label: 'CI Rollback Wired', description: 'Rollback wiring status.' }],
  },
];

export const GCP_SERVERLESS_TEARDOWN_STEPS: ProvisioningStepNode[] = [];
