import type { ProvisioningStepNode } from '../graph.types.js';

export const GITHUB_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'github:create-repository',
    label: 'Create Repository',
    description: 'Create or link the GitHub repository for the project.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'user:provide-github-pat', required: true }],
    inputFields: [
      {
        key: 'github_owner',
        label: 'GitHub Owner / Org',
        description: 'Optional override for where the repository should be created (user or organization name).',
        type: 'text',
        placeholder: 'my-org',
        required: false,
      },
    ],
    produces: [
      {
        key: 'github_repo_url',
        label: 'Repository',
        description: 'GitHub repository URL (opens in browser)',
      },
    ],
    estimatedDurationMs: 5000,
  },
  {
    type: 'step',
    key: 'github:deploy-workflows',
    label: 'Deploy CI/CD Workflows',
    description:
      'Create CI/CD workflow YAML files for selected deploy targets and their app roots, Dockerfiles, and build contexts.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'github:create-repository', required: true }],
    inputFields: [
      {
        key: 'deploy_target_types',
        label: 'Deploy Target Types',
        description:
          'Pick one or more target types for CI/CD workflow generation. Defaults are auto-detected from selected modules when left unchanged.',
        type: 'multiselect',
        options: ['mobile', 'web', 'api'],
        required: true,
      },
      {
        key: 'deploy_mobile_stack',
        label: 'Mobile Stack',
        description: 'Select the supported mobile CI/CD stack.',
        type: 'select',
        options: ['expo'],
        defaultValue: 'expo',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['mobile'],
        },
      },
      {
        key: 'deploy_web_stack',
        label: 'Web Stack',
        description: 'Select the supported web UI stack.',
        type: 'select',
        options: ['react', 'nextjs'],
        defaultValue: 'react',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_web_destination',
        label: 'Web Deployment Target',
        description: 'Select where the web app should be deployed.',
        type: 'select',
        options: ['gcp-cloud-run'],
        defaultValue: 'gcp-cloud-run',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_web_root',
        label: 'Web App Root',
        description: 'Repository-relative web app directory. Use apps/web for fullstack monorepos.',
        type: 'text',
        defaultValue: 'apps/web',
        placeholder: 'apps/web',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_web_dockerfile',
        label: 'Web Dockerfile',
        description: 'Repository-relative Dockerfile for the web Cloud Run image.',
        type: 'text',
        defaultValue: 'apps/web/Dockerfile',
        placeholder: 'apps/web/Dockerfile',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_web_build_context',
        label: 'Web Build Context',
        description: 'Docker build context. Use "." when the web app imports shared packages from the repo.',
        type: 'text',
        defaultValue: '.',
        placeholder: '.',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_api_stack',
        label: 'API Stack',
        description: 'Select the supported API stack.',
        type: 'select',
        options: ['node/express', 'flask'],
        defaultValue: 'node/express',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_destination',
        label: 'API Deployment Target',
        description: 'Select where the API should be deployed.',
        type: 'select',
        options: ['gcp-cloud-run'],
        defaultValue: 'gcp-cloud-run',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_root',
        label: 'API App Root',
        description: 'Repository-relative API service directory. Use apps/api for fullstack monorepos.',
        type: 'text',
        defaultValue: 'apps/api',
        placeholder: 'apps/api',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_dockerfile',
        label: 'API Dockerfile',
        description: 'Repository-relative Dockerfile for the API Cloud Run image.',
        type: 'text',
        defaultValue: 'apps/api/Dockerfile',
        placeholder: 'apps/api/Dockerfile',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_build_context',
        label: 'API Build Context',
        description: 'Docker build context. Use "." when the API imports shared packages from the repo.',
        type: 'text',
        defaultValue: '.',
        placeholder: '.',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_health_path',
        label: 'API Health Path',
        description: 'HTTP path used for API smoke checks after deployment.',
        type: 'text',
        defaultValue: '/api/health',
        placeholder: '/api/health',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
    ],
    produces: [],
    estimatedDurationMs: 5000,
  },
];

export const GITHUB_TEARDOWN_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'github:delete-workflows',
    label: 'Delete GitHub Workflows',
    description: 'Remove repository workflow files and CI/CD automation.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    direction: 'teardown',
    teardownOf: 'github:deploy-workflows',
    dependencies: [],
    produces: [],
  },
  {
    type: 'step',
    key: 'github:delete-repository',
    label: 'Delete Source Repository',
    description: 'Delete the GitHub repository for this project.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'assisted',
    direction: 'teardown',
    teardownOf: 'github:create-repository',
    dependencies: [{ nodeKey: 'github:delete-workflows', required: true }],
    produces: [],
  },
];
