import type { ProvisioningStepNode } from '../graph.types.js';

export const GITHUB_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'github:create-repository',
    label: 'Create Repository',
    description: 'Create or link the GitHub repository for the project.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'user:provide-github-pat', required: true }],
    inputFields: [
      {
        key: 'github_owner',
        label: 'GitHub Owner / Org',
        description: 'Optional override for where the repository should be created (user or organization name).',
        type: 'text',
        placeholder: 'my-org',
        required: false,
      },
    ],
    produces: [
      {
        key: 'github_repo_url',
        label: 'Repository',
        description: 'GitHub repository URL (opens in browser)',
      },
    ],
    estimatedDurationMs: 5000,
  },
  {
    type: 'step',
    key: 'github:deploy-workflows',
    label: 'Deploy CI/CD Workflows',
    description: 'Create CI/CD workflow YAML files for the selected deploy targets (mobile, web, api).',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    dependencies: [{ nodeKey: 'github:create-repository', required: true }],
    inputFields: [
      {
        key: 'deploy_target_types',
        label: 'Deploy Target Types',
        description:
          'Pick one or more target types for CI/CD workflow generation. Defaults are auto-detected from selected modules when left unchanged.',
        type: 'multiselect',
        options: ['mobile', 'web', 'api'],
        required: true,
      },
      {
        key: 'deploy_mobile_stack',
        label: 'Mobile Stack',
        description: 'Select the supported mobile CI/CD stack.',
        type: 'select',
        options: ['expo'],
        defaultValue: 'expo',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['mobile'],
        },
      },
      {
        key: 'deploy_web_stack',
        label: 'Web Stack',
        description: 'Select the supported web UI stack.',
        type: 'select',
        options: ['react', 'nextjs'],
        defaultValue: 'react',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_web_destination',
        label: 'Web Deployment Target',
        description: 'Select where the web app should be deployed.',
        type: 'select',
        options: ['gcp-cloud-run'],
        defaultValue: 'gcp-cloud-run',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['web'],
        },
      },
      {
        key: 'deploy_api_stack',
        label: 'API Stack',
        description: 'Select the supported API stack.',
        type: 'select',
        options: ['node/express', 'flask'],
        defaultValue: 'node/express',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
      {
        key: 'deploy_api_destination',
        label: 'API Deployment Target',
        description: 'Select where the API should be deployed.',
        type: 'select',
        options: ['gcp-cloud-run'],
        defaultValue: 'gcp-cloud-run',
        required: true,
        dependsOn: {
          fieldKey: 'deploy_target_types',
          includesAny: ['api'],
        },
      },
    ],
    produces: [],
    estimatedDurationMs: 5000,
  },
];

export const GITHUB_TEARDOWN_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'github:delete-workflows',
    label: 'Delete GitHub Workflows',
    description: 'Remove repository workflow files and CI/CD automation.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'full',
    direction: 'teardown',
    teardownOf: 'github:deploy-workflows',
    dependencies: [],
    produces: [],
  },
  {
    type: 'step',
    key: 'github:delete-repository',
    label: 'Delete Source Repository',
    description: 'Delete the GitHub repository for this project.',
    provider: 'github',
    environmentScope: 'global',
    automationLevel: 'assisted',
    direction: 'teardown',
    teardownOf: 'github:create-repository',
    dependencies: [{ nodeKey: 'github:delete-workflows', required: true }],
    produces: [],
  },
];
