import type { ProvisioningStepNode } from '../graph.types.js';

export const GOOGLE_PLAY_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'google-play:create-app-listing',
    label: 'Create Play Console Listing',
    description: 'Create the app in Google Play Console.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    platforms: ['android'],
    dependencies: [{ nodeKey: 'user:enroll-google-play', required: true }],
    produces: [
      {
        key: 'play_app_id',
        label: 'Play App ID',
        description: 'Google Play application ID',
      },
    ],
    estimatedDurationMs: 5000,
  },
  {
    type: 'step',
    key: 'google-play:create-service-account',
    label: 'Create Play Service Account',
    description:
      'Create a GCP service account with Play Console API access for automated uploads.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    platforms: ['android'],
    dependencies: [
      { nodeKey: 'google-play:create-app-listing', required: true },
      {
        nodeKey: 'firebase:create-gcp-project',
        required: true,
        description: 'SA created in the same GCP project',
      },
    ],
    produces: [
      {
        key: 'play_service_account_email',
        label: 'Play SA',
        description: 'Service account for Play Console API',
      },
    ],
    estimatedDurationMs: 8000,
  },
  {
    type: 'step',
    key: 'google-play:setup-internal-testing',
    label: 'Set Up Internal Testing Track',
    description: 'Configure the internal testing track for development builds.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    platforms: ['android'],
    dependencies: [
      { nodeKey: 'google-play:create-app-listing', required: true },
      { nodeKey: 'user:upload-initial-aab', required: true },
    ],
    produces: [],
    estimatedDurationMs: 3000,
  },
  {
    type: 'step',
    key: 'google-play:configure-app-signing',
    label: 'Configure App Signing',
    description: 'Enable Google-managed signing and delegate upload key.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    platforms: ['android'],
    dependencies: [
      { nodeKey: 'google-play:create-app-listing', required: true },
      { nodeKey: 'user:upload-initial-aab', required: true },
    ],
    produces: [],
    estimatedDurationMs: 3000,
  },
  {
    type: 'step',
    key: 'google-play:extract-fingerprints',
    label: 'Extract Signing Fingerprints',
    description: 'Extract SHA-1 and SHA-256 fingerprints from the Google-managed signing key.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    platforms: ['android'],
    dependencies: [{ nodeKey: 'google-play:configure-app-signing', required: true }],
    produces: [
      {
        key: 'signing_sha1',
        label: 'SHA-1',
        description: 'Signing certificate SHA-1 fingerprint',
      },
      {
        key: 'signing_sha256',
        label: 'SHA-256',
        description: 'Signing certificate SHA-256 fingerprint',
      },
    ],
    estimatedDurationMs: 3000,
  },
  {
    type: 'step',
    key: 'google-play:add-fingerprints-to-firebase',
    label: 'Add Fingerprints to Firebase',
    description:
      'Register signing fingerprints with the Firebase Android app for OAuth and deep links.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'full',
    bridgeTarget: 'firebase',
    platforms: ['android'],
    dependencies: [
      { nodeKey: 'google-play:extract-fingerprints', required: true },
      { nodeKey: 'firebase:register-android-app', required: true },
    ],
    produces: [],
    estimatedDurationMs: 3000,
  },
];

export const GOOGLE_PLAY_TEARDOWN_STEPS: ProvisioningStepNode[] = [
  {
    type: 'step',
    key: 'google-play:revoke-service-account',
    label: 'Revoke Play Service Account',
    description: 'Remove Google Play API access service account permissions.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'assisted',
    direction: 'teardown',
    teardownOf: 'google-play:create-service-account',
    platforms: ['android'],
    dependencies: [],
    produces: [],
  },
  {
    type: 'step',
    key: 'google-play:remove-app-listing',
    label: 'Remove Play Console Listing',
    description: 'Delete the app listing from Google Play Console.',
    provider: 'google-play',
    environmentScope: 'global',
    automationLevel: 'manual',
    direction: 'teardown',
    teardownOf: 'google-play:create-app-listing',
    platforms: ['android'],
    dependencies: [{ nodeKey: 'google-play:revoke-service-account', required: true }],
    produces: [],
  },
];
